# Generated by Django 3.2.7 on 2022-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_alter_uploadimagetest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagetest',
            name='time',
            field=models.TimeField(default='12:44:28'),
        ),
    ]
